package-lock.json, package.json, src/app.js, src/controllers/auth.controller.js, src/controllers/board.controller.js, src/controllers/challenge.controller.js, src/controllers/challenge/category.controller.js, src/controllers/challenge/list.controller.js, src/controllers/challenge/participation.controller.js, src/controllers/message.controller.js, src/controllers/post.controller.js, src/controllers/users.controller.js, src/controllers/verification/comment.controller.js, src/controllers/verification/like.controller.js, src/controllers/verification/scrap.controller.js, src/controllers/verification/verification.controller.js, src/index.js, src/routes/auth.routes.js, src/routes/board.routes.js, src/routes/challenge.routes.js, src/routes/message.routes.js, src/routes/post.routes.js, src/routes/users.routes.js, src/routes/verification.routes.js
- Swagger를 통해 API를 표기했습니다.
- API 명세를 swagger를 이용해 나타냄
- 빈 controller를 구현하여 swagger을 작성함.
- router를 통해 디렉토리 구조를 나눔
=> Feat: Add swagger annotations

package-lock.json, package.json, prisma/schema.prisma, prisma/seed.js, src/app.js, src/controllers/auth.controller.js, src/controllers/board.controller.js, src/controllers/challenge.controller.js, src/controllers/challenge/category.controller.js, src/controllers/challenge/list.controller.js, src/controllers/challenge/participation.controller.js, src/controllers/message.controller.js, src/controllers/post.controller.js, src/controllers/users.controller.js, src/controllers/verification/comment.controller.js, src/controllers/verification/like.controller.js, src/controllers/verification/scrap.controller.js, src/controllers/verification/verification.controller.js, src/db.config.js, src/index.js, src/routes/auth.routes.js, src/routes/board.routes.js, src/routes/challenge.routes.js, src/routes/message.routes.js, src/routes/post.routes.js, src/routes/users.routes.js, src/routes/verification.routes.js
- 프로젝트 기초 세팅을 마무리합니다.
- Prisma를 이용한 DB 세팅을 마무리합니다.
- Swagger을 이용한 API명세를 배포합니다.
=> [Pre-work] DB, Swagger 세팅 완료

prisma/migrations/20250116111044_localv1/migration.sql, prisma/schema.prisma, src/db.config.js
- 테스트용 DB 서버를 구축하고 연결하였습니다.
- 기존 RDS의 DB가 public 접근이 제한되어 있어 api test환경에서는 사용할 수 없었습니다. 이를 해결하기 위해 테스트용 DB를 구축하고, 도메인을 연결하였습니다.
- .env 파일을 업데이트하과 공유하였습니다.
=> Chore: Link test DB server

src/controllers/auth.controller.js, src/repositories/auth.repository.js, src/services/auth.service.js
- JSON response 형식을 수정하였습니다.
- 중괄호가 한겹씩 더 들어가 있던 것을 해결했습니다.
- 불필요한 정보까지 넘겨주는 것을 줄였습니다.
=> Refactor: Fix json braces

src/controllers/board.controller.js, src/controllers/challenge/list.controller.js, src/dtos/challenge/list.dto.js, src/errors/board.error.js, src/repositories/board.repository.js, src/repositories/challenge/list.repository.js, src/routes/board.routes.js, src/services/auth.service.js, src/services/board.service.js, src/utils/cronjobs.util.js, src/utils/sendmail.util.js
- 게시판을 상단에 고정하고, 고정 해제하는 api를 구현했습니다.
- controller를 제외한 함수들은 status를 인자로 받아  재활용했습니다.
=> Feat: Add board pin, unpin api

src/middlewares/auth.middleware.js
- 토큰에서 문제가 있을 경우 서버가 다운 되는 문제를 해결했습니다.
- 에러가 생겼을 때 throw를 사용하던 부분을 미들웨어를 통하도록 수정하였습니다.
- 코딩 컨벤션은 snake_case로 전부 통일했습니다.
=> Fix: Token server error

src/controllers/users.controller.js, src/dtos/user.dto.js, src/errors/users.error.js, src/repositories/users.repository.js, src/routes/users.routes.js, src/services/users.service.js
- 사용자의 진행 중인 챌린지 조회하기 기능 구현
- 챌린지 Id, 제목, 사진을 조회할 수 있도록 구현하였습니다.
- 
타입 추가 버전
- 인증 완료 여부 체크 부분 추가해야 합니다.
=> Feat/#34 user-challenge-ongoing

prisma/migrations/20250126151715_/migration.sql, prisma/schema.prisma, prisma/seed.js, prisma/seed.sql
- 데이터베이스 변경 작업을 수행합니다.
- duration 컬럼을 추가합니다.
- duration 컬럼의 enum 내용을 수정합니다. (month와 year을 추가합니다.)
- status로 변수명을 변경합니다. 
- 변경한 데이터베이스를 npm exec prisma migrate dev  진행합니다. 
- 변경한 데이터베이스 내용을 바탕으로 seed 파일을 수정합니다.
=> Fix: Database change

src/controllers/users.controller.js, src/dtos/user.dto.js, src/errors/users.error.js, src/repositories/users.repository.js, src/routes/users.routes.js, src/services/users.service.js
- 사용자가 완주한 챌린지를 보여주는 기능입니다.
- 챌린지의 id, 이름, 사진, 한 줄 설명을 조회할 수 있습니다.
- email을 사용하여 사용자를 찾습니다.
=> 최근 완주한 챌린지 API

prisma/migrations/20250128090033_/migration.sql, prisma/schema.prisma, src/controllers/auth.controller.js, src/dtos/auth.dto.js, src/errors/auth.error.js, src/repositories/auth.repository.js, src/services/auth.service.js
- 회원가입 시 닉네임을 입력받게 수정하였습니다.
- 회원 가입 시 닉네임을 입력받게 수정하였습니다.
- DB에서 user테이블의 status 항목을 삭제하였습니다.
=> Fix: Add nickname in register logic

.github/workflows/deploy-main.yml
- deploy-main.yml 파일의 npm run dev를 npm start로 수정하였습니다.
=> Fix: fix deploy-main.yml npm run dev to npm start

prisma/schema.prisma
- 불필요한 데이터베이스를 삭제합니다.
- Vericication 테이블에서 challengeType, deadline, status  컬럼을 삭제합니다.
- Badges 테이블에서 profileImage, description 컬럼을 삭제합니다.
=> Fix: Database change - Delete unnecessary column

src/controllers/users.controller.js, src/dtos/user.dto.js, src/errors/users.error.js, src/repositories/users.repository.js, src/routes/users.routes.js, src/services/users.service.js
=> Feat: 사용자 팔로우

src/controllers/users.controller.js, src/dtos/user.dto.js, src/errors/users.error.js, src/repositories/users.repository.js, src/routes/users.routes.js, src/services/users.service.js
=> Feat: 사용자 언팔로우

src/app.js, src/index.js
- morganMiddleware와 error logger을 수정했습니다.
- http 요청이 로깅이 안되던 문제를 해결했습니다.
- 에러가 발생시 로그가 제대로 남지 않던 문제를 해결했습니다.
=> Fix: Fix morganMiddleware & error logger

src/controllers/users.controller.js, src/dtos/user.dto.js, src/repositories/users.repository.js, src/routes/users.routes.js, src/services/users.service.js
- 배지 조건을 조회하며 사용자의 조건 획득 여부를 조회합니다.
- Endpoint: /api/v1/users/badges/conditions
- route 및 swagger 추가
- 결과
=> Feat: 배지 조건 조회

src/docs/swagger.json, src/docs/swagger/user.json
- swagger에 맞지 않던 엔드포인트들을 수정했습니다.
=> Fix: Swagger Annotation error

src/docs/swagger.json, src/docs/swagger/user.json
- 스웨거 주석 변경 작업중 누락된 커밋을 메인에 머지합니다.
- 엔드포인트 수정 커밋이 반영이 되지 않았습니다.
=> Hotfix: swagger endpoint error

prisma/migrations/20250131182958_add_level_condition_and_user_level/migration.sql, prisma/migrations/20250201091029_edit_type_to_enum/migration.sql, prisma/schema.prisma, src/controllers/users.controller.js, src/dtos/user.dto.js, src/repositories/users.repository.js, src/routes/users.routes.js, src/services/users.service.js
- 레벨 화면을 조회합니다.
- 현재 레벨, 포인트, 레벨 조건 id, 조건, 조건 획득 여부를 조회합니다.
- 데이터 베이스 수정했습니다.
- Level_Condition, UserLevel 테이블을 추가했습니다.
=> Feat: 레벨 화면 조회

src/controllers/auth.controller.js, src/docs/swagger.json, src/docs/swagger/auth.json
- email-login api의 response에 userId를 추가합니다.
- RefreshToken을 통해 AccessToken을 반환하는 api가 제대로 작동하지 않던 오류를 해결했습니다.
=> Fix: add userId to login api

prisma/schema.prisma, src/controllers/auth.controller.js, src/docs/swagger.json, src/docs/swagger/participation.json, src/repositories/challenge/list.repository.js, src/repositories/challenge/participation.repository.js
- 챌린지 참가시 참가자수 증가 안됨
- 챌린지에 참가하는 경우 해당 챌린지의 사람 수가 증가하지 않는 문제를 수정했습니다.
- response에 userchallenge table의 내용이 들어가는 것을 challenge내용으로 수정했습니다.
=> Fix: join-challenge-api, add currentParticipants increase logic

src/dtos/user.dto.js
- 해당 사용자의 모든 인증 기록이 출력되도록 수정하였습니다. 
1. map → flatMap
2. find → filter
3. 반환할 때 map으로 묶어서 다시 객체로 보냄
=> [Bug]모든 인증 기록 출력

src/controllers/auth.controller.js, src/docs/swagger.json, src/docs/swagger/auth.json, src/dtos/auth.dto.js, src/repositories/auth.repository.js, src/routes/auth.routes.js, src/routes/users.routes.js, src/services/auth.service.js
- 닉네임 중복 확인 api를 구현합니다.
- request header
```json
{
"nickname" : "김흐르"
}
```
- request body
```json
{
"resultType": "SUCCESS",
"error": null,
"success": {
"check": false
}
}
```
- 중복 : true, 중복 x: false
=> Feat: nickname-check api

src/controllers/users.controller.js, src/docs/swagger.json, src/docs/swagger/user.json, src/dtos/user.dto.js, src/repositories/users.repository.js, src/routes/users.routes.js, src/services/users.service.js
- 사용자가 최근 획득한 배지를 조회하는 기능입니다.
- badge_id, name, icon, type을 조회합니다.
=> [Feat] 최근 획득한 배지 조회

prisma/migrations/20250214144337_/migration.sql, prisma/schema.prisma, src/controllers/users.controller.js, src/docs/swagger.json, src/docs/swagger/user.json, src/errors/auth.error.js, src/repositories/users.repository.js, src/routes/auth.routes.js, src/routes/users.routes.js, src/services/auth.service.js, src/services/users.service.js
- 이메일 인증 관련 로직을 수정했습니다.
- 기존 : 이미 존재하는 이메일일 경우 확인 메일 안보냄
- 수정 : 확인 메일은 항상 보내고 register api에서 이메일이 존재하면 에러 반환
=> Feat: change email-verification-logic

package-lock.json, package.json, src/controllers/auth.controller.js, src/controllers/verification/verification.controller.js, src/docs/swagger/verification.json, src/dtos/verification/verification.dto.js, src/middlewares/uploadMiddleware.js, src/repositories/users.repository.js, src/routes/verification.routes.js, src/services/auth.service.js, src/services/verification/verification.service.js, src/utils/s3Uploader.js
- 사진을 전송받고 S3에 업로드 후 url을 반환하는 로직을 추가했습니다!
- <img width="1287" alt="image" src="https://github.com/user-attachments/assets/3ad62e98-66ce-4e35-ba16-afa8952354e9" />
- <img width="1266" alt="image" src="https://github.com/user-attachments/assets/68f16a80-2ade-431b-a13f-41a92422be6d" />
=> Feat: Add S3 upload logic!!!!

prisma/migrations/20250215143342_/migration.sql, prisma/migrations/20250215144434_/migration.sql, prisma/migrations/20250215144754_y/migration.sql, prisma/schema.prisma, src/controllers/challenge/like.controller.js, src/controllers/challenge/scrap.controller.js, src/docs/swagger/like.json, src/docs/swagger/scrap.json, src/dtos/challenge/like.dto.js, src/dtos/challenge/scrap.dto.js, src/errors/auth.error.js, src/repositories/challenge/like.repository.js, src/repositories/challenge/scrap.repository.js, src/routes/challenge.routes.js, src/services/challenge/like.service.js, src/services/challenge/scrap.service.js
- 챌린지 좋아요, 스크랩, 좋아요취소, 스크랩 취소를 구현합니다.
- 해당 모든 사항은 인증 좋아요, 스크랩과 똑같습니다.
=> Feat: Challenge scrap, like

src/docs/swagger/auth.json, src/repositories/auth.repository.js, src/services/auth.service.js
- 회원가입 api의 response를 변경합니다.
- 회원가입 api에 
- userId
- accessToken,
- refreshToken
을 추가합니다.
=> Fix: register response type

src/controllers/users.controller.js, src/docs/swagger/user.json, src/repositories/challenge/like.repository.js, src/repositories/challenge/scrap.repository.js, src/repositories/users.repository.js
- 팔로워 팔로잉 조회 api에 level을 추가합니다.
=> Feat: fix swagger on following

prisma/migrations/20250215163739_/migration.sql, prisma/schema.prisma, src/controllers/users.controller.js, src/docs/swagger/user.json, src/dtos/user.dto.js, src/repositories/challenge/like.repository.js, src/repositories/users.repository.js, src/routes/users.routes.js, src/services/users.service.js
- 챌린지를 추천해주는 기능입니다.
- auth 사용
- 관심사 추가 및 수정 가능하도록 구현
- 한 번에 랜덤으로 9개씩 불러오며 9개보다 적은 수의 챌린지는 양대로 불러옴
- like.repository.js에서 likeError 불러오는 부분이 에러가 나서 수정하였습니다
=> [Feat] 챌린지 추천

src/controllers/users.controller.js, src/docs/swagger/user.json, src/dtos/user.dto.js, src/repositories/users.repository.js, src/services/users.service.js
- id로 사용자 불러오도록 변경
- 스웨거 name -> nickname
- null인 경우 배지 취소
- null 값을 뒤로 배치
=> [bug] 배지 변경 수정

src/controllers/auth.controller.js, src/docs/swagger/auth.json, src/services/auth.service.js
- 카카오 로그인 response에 user_id 추가
=> [Bug] 카카오 로그인 response에 user_id 추가

src/docs/swagger/user.json, src/dtos/user.dto.js, src/repositories/users.repository.js, src/services/users.service.js
- 배지 조건 충족 시 자동으로 배지 획득하는 기능입니다.
- 반환 내용에 배지 isObtained 추가
=> [bug] 배지 조건 충족 시 자동으로 배지 획득

src/repositories/auth.repository.js, src/repositories/board.repository.js, src/repositories/challenge/category.repository.js, src/repositories/challenge/like.repository.js, src/repositories/challenge/list.repository.js, src/repositories/challenge/participation.repository.js, src/repositories/challenge/scrap.repository.js, src/repositories/users.repository.js, src/repositories/verification/comment.repository.js, src/repositories/verification/like.repository.js, src/repositories/verification/scrap.repository.js, src/repositories/verification/verification.repository.js
- 진작에 이랬어야 했어요...
- 예상하지 못한 에러는 로그에 다 남게 수정했습니다.
- /error/html에서 확인 가능합니다.
=> Chore: add logger to unexpected problems
